# * COMPLETED
smollm2:135m:
    native_thinking_mode: false
    billion_params: 0.135

gemma4:e4b:
    native_thinking_mode: true
    billion_params: 8.0

gemma3:1b:
    native_thinking_mode: false
    billion_params: 1.0

codestral:22b:
    native_thinking_mode: false
    billion_params: 22

qwen2.5-coder:14b:
    native_thinking_mode: false
    billion_params: 14.8

qwen3:4b-thinking:
    native_thinking_mode: true
    billion_params: 4.0

# TODO: verify the above data is correct
